In [134]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [135]:
path=r'F:\Data_science_with_python\Graded_assessment\amsterdam.json'
data=pd.read_json(path)

In [140]:
import sklearn.ensemble as ensemble

In [141]:
data.isnull().sum()

host_listings_count                3
accommodates                       0
bathrooms                         18
bedrooms                          12
guests_included                    0
minimum_nights                     0
number_of_reviews                  0
calculated_host_listings_count     0
price                              0
latitude                           0
longitude                          0
room_type                          0
instant_bookable                   0
dtype: int64

In [143]:
data[data.isnull().any(axis=1)]

host_listings_count  accommodates  bathrooms  bedrooms  \
10069                  1.0             2        1.0       NaN   
10096                  3.0             2        NaN       1.0   
10097                  1.0             2        1.0       NaN   
10188                  1.0             2        1.0       NaN   
10360                  2.0             2        NaN       1.0   
11165                  4.0             2        NaN       1.0   
11969                  1.0             2        NaN       1.0   
12893                  1.0             2        NaN       1.0   
1321                   2.0             2        NaN       1.0   
1324                   2.0             2        NaN       1.0   
1369                   2.0             3        NaN       2.0   
14498                  NaN             2        1.0       1.0   
14989                  2.0             2        NaN       1.0   
1852                   1.0             2        1.0       NaN   
2561                   3.0             2        NaN       1.0   
2753                   1.0             2        1.0       NaN   
2837                   2.0             2        NaN       1.0   
345                    1.0             4        NaN       1.0   
3582                   1.0             1        NaN       1.0   
4243                   NaN             2        1.0       1.0   
4441                   1.0             2        1.0       NaN   
4985                   2.0             2        NaN       1.0   
5573                   1.0             2        NaN       1.0   
6965                   1.0             2        NaN       1.0   
6967                   1.0             2        0.5       NaN   
7673                   NaN             4        1.0       1.0   
8                      3.0             2        NaN       1.0   
8038                   2.0             3        NaN       1.0   
8737                   1.0             2        1.0       NaN   
8919                   1.0             2        1.0       NaN   
925                    5.0            13        0.5       NaN   
9938                   1.0             1        2.0       NaN   
9987                   1.0             2        1.0       NaN   

       guests_included  minimum_nights  number_of_reviews  \
10069                1               2                  5   
10096                1               1                  4   
10097                1               3                  0   
10188                1               3                  0   
10360                2               2                166   
11165                1               2                134   
11969                1               6                  8   
12893                1               2                 33   
1321                 1               1                  1   
1324                 1               1                  4   
1369                 2               3                112   
14498                1               1                  1   
14989                1               2                  6   
1852                 1               1                  0   
2561                 1               2                 63   
2753                 1               3                 20   
2837                 1               2                110   
345                  2               2                  1   
3582                 2               1                 11   
4243                 2               3                 20   
4441                 1               1                  0   
4985                 1               3                 20   
5573                 2               2                129   
6965                 2               2                  2   
6967                 1               2                  0   
7673                 1               3                 19   
8                    1               1                  2   
8038                 3               2                268   
8737                 1     

In [144]:
# Dropping the rows which are null
data_new=data.drop(data[data.isnull().any(axis=1)].index)

In [15]:
#data_new=data.drop(['latitude','longitude'],axis=1)

In [146]:
data.shape

(15181, 13)

In [147]:
data_new.shape

(15148, 13)

In [148]:
import sklearn.preprocessing as pre

In [149]:
enc=pre.LabelEncoder()

In [150]:
data_new['room_type']=enc.fit_transform(data_new['room_type'])

In [151]:
enc.classes_

array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)

In [152]:
enc_instant_bookable=pre.LabelEncoder()
data_new['instant_bookable']=enc_instant_bookable.fit_transform(data_new['instant_bookable'])

In [27]:
#data_new.boxplot(by='accommodates',column='price')

In [155]:
# to remove special character from price column
import re
data_new['price']=data_new['price'].map(lambda x:re.sub('[^A-Za-z0-9]+', '', x))

In [131]:
#data_new['price']=data_new.price.str[1:]

In [157]:
import sklearn.model_selection as model
X=data_new.drop('price', axis=1)
Y=data_new['price']
X_train, X_test, Y_train, Y_test = model.train_test_split(X,Y, random_state=200, test_size=0.20)

In [158]:
X_train.shape

(12118, 12)

In [159]:
X_test.shape

(3030, 12)

In [209]:
model=ensemble.RandomForestRegressor(n_estimators=100, n_jobs=-1)

In [213]:
model=model.fit(X_train,Y_train)

In [214]:
model.predict(X_test)

array([12593., 13826., 11390., ..., 17339.,  9552., 10652.])

In [219]:
model.score(X_test, Y_test)

0.3822968520816298

In [168]:
## how many trees should be there
for i in [200, 300, 400, 500, 600]:
    mod=ensemble.RandomForestRegressor(n_estimators=i, n_jobs=-1)
    mod=mod.fit(X_train, Y_train)
    print(mod.score(X_test, Y_test))

0.38321491965473153
0.3829205518550536
0.38911974787729353
0.38349815858959235
0.3852840090493298


In [169]:
import statsmodels.formula.api as smf

In [211]:
gb_model=ensemble.GradientBoostingRegressor(n_estimators=100)

In [212]:
model1=gb_model.fit(X_train,Y_train)

In [173]:
model1.score(X_test, Y_test) # MSE - Mean Square Error

0.3572443692232752

In [175]:
model.feature_importances_

array([0.01815255, 0.27285245, 0.07292303, 0.05336878, 0.05506547,
       0.0660101 , 0.08190619, 0.02533811, 0.14416355, 0.16479195,
       0.03416525, 0.01126256])

In [176]:
model1.feature_importances_

array([0.00664677, 0.32029274, 0.07830808, 0.20034037, 0.06652405,
       0.04585329, 0.03496202, 0.02231559, 0.05810062, 0.11524366,
       0.04918606, 0.00222676])

In [222]:
pd.Series(model.feature_importances_,index=x.columns).sort_values(ascending=False)

accommodates                      0.276027
longitude                         0.170144
latitude                          0.143414
number_of_reviews                 0.082615
bathrooms                         0.071096
minimum_nights                    0.064513
guests_included                   0.055107
bedrooms                          0.052792
room_type                         0.035161
calculated_host_listings_count    0.022890
host_listings_count               0.016801
instant_bookable                  0.009439
dtype: float64

In [223]:
pd.Series(model1.feature_importances_,index=x.columns).sort_values(ascending=False)

accommodates                      0.320193
bedrooms                          0.196776
longitude                         0.109574
bathrooms                         0.078354
latitude                          0.067015
guests_included                   0.066369
room_type                         0.048374
minimum_nights                    0.047273
number_of_reviews                 0.038253
calculated_host_listings_count    0.023932
instant_bookable                  0.002227
host_listings_count               0.001660
dtype: float64

In [224]:
from sklearn.ensemble.partial_dependence import plot_partial_dependence

In [225]:
x=data_new.drop('price',axis=1)
y=data_new['price']

In [226]:
import sklearn.model_selection as model_selection
param_grid={'n_estimators':[110,120],'learning_rate':[0.05,0.07],'max_depth':[3,5]}
mod1=model_selection.GridSearchCV(ensemble.GradientBoostingRegressor(),
                                  param_grid=param_grid,n_jobs=-1,cv=3)

In [227]:
mod1.fit(X_train,Y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_sampl...=None, subsample=1.0, tol=0.0001,
             validation_fraction=0.1, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'n_estimators': [110, 120], 'learning_rate': [0.05, 0.07], 'max_depth': [3, 5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [228]:
mod1.best_params_

{'learning_rate': 0.07, 'max_depth': 3, 'n_estimators': 120}

In [229]:
mod1.predict(X_test)

array([13096.85244566, 14339.33983422, 10940.64082851, ...,
       16658.21672046, 10057.43363901, 10548.31620833])

In [230]:
model.decision_path(X_test)

(<3030x1377974 sparse matrix of type '<class 'numpy.int64'>'
 	with 6119303 stored elements in Compressed Sparse Row format>,
 array([      0,   13845,   27640,   41481,   55230,   69061,   82800,
          96631,  110436,  124103,  137898,  151725,  165572,  179421,
         193222,  206963,  220740,  234471,  248248,  261957,  275790,
         289539,  303324,  317049,  330748,  344555,  358252,  372021,
         385884,  399701,  413580,  427347,  441100,  454811,  468514,
         482327,  496148,  509845,  523564,  537389,  551108,  564967,
         578760,  592571,  606326,  620091,  633852,  647589,  661272,
         674935,  688764,  702575,  716186,  729959,  743734,  757411,
         771204,  784921,  798650,  812351,  826026,  839901,  853772,
         867537,  881338,  895145,  908866,  922631,  936482,  950257,
         964034,  977779,  991562, 1005317, 1018972, 1032807, 1046612,
        1060327, 1073952, 1087821, 1101558, 1115495, 1129324, 1143121,
        1156986, 11708

In [231]:
import os

In [232]:
import pydotplus

In [202]:
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

In [238]:
from sklearn import tree
dot_data = tree.export_graphviz(model,out_file=None,feature_names=X_train.columns,filled=True,rounded=True,special_characters=True)

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.